apiVersion: v1
kind: Namespace
metadata:
  name: sharekube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sharekube-controller-manager
  namespace: sharekube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharekube-manager-role
rules:
- apiGroups:
  - sharekube.dev
  resources:
  - sharekubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharekube.dev
  resources:
  - sharekubes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sharekube.dev
  resources:
  - sharekubes/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sharekube-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharekube-manager-role
subjects:
- kind: ServiceAccount
  name: sharekube-controller-manager
  namespace: sharekube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharekube-controller-manager
  namespace: sharekube-system
  labels:
    app: sharekube-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharekube-controller-manager
  template:
    metadata:
      labels:
        app: sharekube-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: sharekube/operator:latest
        imagePullPolicy: IfNotPresent
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --leader-elect
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: sharekube-controller-manager
      terminationGracePeriodSeconds: 10 