apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database.yaml
- backend.yaml
- frontend.yaml
- configmap.yaml
- sharekube.yaml

# Uncomment to create the namespaces
#- namespace.yaml 