apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: dev
  labels:
    app: sample-app
data:
  app.settings: |
    {
      "apiEndpoint": "/api/v1",
      "logLevel": "info",
      "enableCache": "true"
    } 