name: Build and Push Operator Image

on:
  push:
    branches:
      - main
    paths:
      - 'packages/operator/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/operator
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=

      - name: Build and push multi-architecture Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/operator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Make package public
        run: |
          echo "NOTE: GitHub Actions doesn't have permission to change package visibility."
          echo "Please manually change the visibility of the package at:"
          echo "https://github.com/users/${{ github.repository_owner }}/packages?repo_name=${{ github.event.repository.name }}"
          echo ""
          echo "Image has been published to:"
          echo "ghcr.io/${{ github.repository }}/operator:latest"
          
          echo "Alternatively, use the local script to build and push to Docker Hub:"
          echo "./scripts/build-multiarch.sh" 